theme: jekyll-theme-slate
title: thkk market AI
description:
  - 感覚に依存しない相場観の構築
# description: "how to make you "rational" with precise and original financial market insight"
# description: Bookmark this to keep an eye on my project updates!
# show_downloads: true
plugins:
  - jemoji

github:
  pages_url: https://thkkmarketai.github.io
  pages_repository_url: https://github.com/thkkmarketai/thkkmarketai.github.io
  pages_name: thkkmarketai.github.io
